FROM ubuntu

WORKDIR /root/

RUN touch ./testfile_1.txt
RUN touch ./testfile_2.txt
RUN touch ./testfile_3.txt

RUN mkdir /root/testfolder/

WORKDIR /root/testfolder/

RUN mkdir ./child_1
RUN mkdir ./child_2
